# Welcome to Jekyll!
#

# Site settings
title: Quick Couriers
description: |
  Quick Courier는 자전거 택배 서비스를 제공하며,  
  교통체증과 무관하게 고객님의 상품을 빠르고 안전하게 배송하는  
  암스테르담의 대표적인 택배 서비스 회사입니다.
owner: Quick Couriers # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://throughkim.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/<username>
  facebook-official: https://facebook.com/<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
